language: python

services:
    - postgresql

install:
    - pip install tox
    - pip install codecov

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - tox -e $TOXENV

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      env: TOXENV=py37

    - python: 3.8
      env: TOXENV=py38

after_success:
  - codecov