version: '3'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
    - ~/DockerVolumes/postgres_bridger:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
    - ~/DockerVolumes/minio_bridger:/data