version: '3'
services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
    - ~/DockerVolumes/postgres_bridger:/var/lib/postgresql/data