site_name: Bridger
theme: readthedocs
nav:
    - Getting started: index.md
    - Serializers: serializers.md
    - Viewsets: viewsets.md
    - Filters: filters.md
    - Workflow: workflow.md
    - Menu: menu.md
    - Scripts: scripts.md
markdown_extensions:
    - admonition
    - markdown_blockdiag:
        format: svg
    - markdown_include.include
plugins:
    - search
