site_name: Bridger
theme: readthedocs
nav:
    - Getting started: index.md
    - Serializers: serializers.md
    - Viewsets: viewsets.md
    - Workflow: workflow.md
markdown_extensions:
    - admonition
