site_name: Bridger

theme:
    name: material

nav:
    - Introduction: index.md
    - Getting started: getting_started.md
    - Serializers: serializers.md
    - Viewsets: viewsets.md
    - Filters: filters.md
    - Workflow: workflow.md
    - Menu: menu.md
    - Websockets: websockets.md
    - Buttons: buttons.md
    - Display: display.md
    - Share: share.md
markdown_extensions:
    - admonition
    - markdown_blockdiag:
        format: svg
    - markdown_include.include
    - codehilite
plugins:
    - search
