# Generated by Django 2.2.9 on 2020-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20200113_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='decimal_field',
            field=models.DecimalField(decimal_places=4, default=3.0, max_digits=7),
            preserve_default=False,
        ),
    ]
