# Generated by Django 2.2.9 on 2020-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_modeltest_decimal_field"),
    ]

    operations = [
        migrations.AddField(model_name="modeltest", name="text_field", field=models.TextField(blank=True, null=True),),
    ]
