# Generated by Django 2.2.10 on 2020-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0011_auto_20200206_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedmodeltest",
            name="model_tests",
            field=models.ManyToManyField(
                null=True,
                related_name="related_models_m2m",
                to="tests.ModelTest",
                verbose_name="Model Tests",
            ),
        ),
    ]
