# Generated by Django 2.2.10 on 2020-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0012_relatedmodeltest_model_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedmodeltest",
            name="model_tests",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_models_m2m",
                to="tests.ModelTest",
                verbose_name="Model Tests",
            ),
        ),
    ]
