# Generated by Django 3.0.5 on 2020-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0018_auto_20200416_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrelatedmodeltest",
            name="text_json",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="relatedmodeltest",
            name="text_json",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
