# Generated by Django 3.0.5 on 2020-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20200416_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelatedmodeltest',
            name='text_markdown',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='relatedmodeltest',
            name='text_markdown',
            field=models.TextField(default=''),
        ),
    ]
