# Generated by Django 3.0.5 on 2020-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20200417_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodeltest',
            name='star_rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltest',
            name='star_rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
