# Generated by Django 3.0.6 on 2020-06-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridger", "0012_tag"),
        ("tests", "0023_auto_20200514_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodeltest", name="tag_detail_endpoint", field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmodeltest",
            name="tag_representation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalrelatedmodeltest", name="tag_detail_endpoint", field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrelatedmodeltest",
            name="tag_representation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(model_name="modeltest", name="tag_detail_endpoint", field=models.URLField(blank=True, null=True),),
        migrations.AddField(
            model_name="modeltest", name="tag_representation", field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(model_name="modeltest", name="tags", field=models.ManyToManyField(blank=True, to="bridger.Tag"),),
        migrations.AddField(
            model_name="relatedmodeltest", name="tag_detail_endpoint", field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedmodeltest",
            name="tag_representation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="relatedmodeltest", name="tags", field=models.ManyToManyField(blank=True, to="bridger.Tag"),
        ),
    ]
