# Generated by Django 3.0.6 on 2020-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridger', '0012_tag'),
        ('tests', '0024_auto_20200609_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodeltest',
            name='file_field',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmodeltest',
            name='image_field',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tests_modeltest_items', to='bridger.Tag'),
        ),
        migrations.AlterField(
            model_name='relatedmodeltest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tests_relatedmodeltest_items', to='bridger.Tag'),
        ),
    ]
