# Generated by Django 3.0.6 on 2020-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0025_auto_20200609_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodeltest",
            name="tag_detail_endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalrelatedmodeltest",
            name="tag_detail_endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="modeltest", name="tag_detail_endpoint", field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="relatedmodeltest",
            name="tag_detail_endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
