# Generated by Django 3.0.8 on 2020-08-04 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_auto_20200609_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelatedmodeltest',
            name='list_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='relatedmodeltest',
            name='list_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
