# Generated by Django 3.1.11 on 2021-05-28 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_auto_20200804_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrelatedmodeltest',
            name='list_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='relatedmodeltest',
            name='list_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
