# Generated by Django 2.2.10 on 2020-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridger", "0002_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="buttons",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
