name: CI

on: [push]

jobs:
  test:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: bridger
          ports:
          - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        redis:
          image: redis:latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: latest
      - name: Install Tox and dependencies
        run: pip install tox
      - name: Run Tox
        run: tox -e py
        env:
          DATABASE_URL: postgres://root:root@localhost:5432/bridger
      - uses: codecov/codecov-action@v1
        with:
          name: Uploading Coverage Report to Codecov
          token: ${{ secrets.CODECOV_TOKEN }}